Document: daemonize
Title: Debian daemonize Manual
Author: <insert document author here>
Abstract: This manual describes what daemonize is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/daemonize/daemonize.sgml.gz

Format: postscript
Files: /usr/share/doc/daemonize/daemonize.ps.gz

Format: text
Files: /usr/share/doc/daemonize/daemonize.text.gz

Format: HTML
Index: /usr/share/doc/daemonize/html/index.html
Files: /usr/share/doc/daemonize/html/*.html
